name: ci-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: bdockerimg/quicklisp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Git
        run: apt update && apt install -y git
      - name: Run Tests
        env:
          COVERALLS: 'true'
          COVERALLS_REPO_TOKEN: 'COVERALLS_REPO_TOKEN=AjlQRo6hsAc6TsTv0tTXXW1AWR0MuFJQP'
        run: |
          set -ex
          sbcl --disable-debugger \
               --load /root/quicklisp/setup.lisp \
               --eval '(ql:update-all-dists)' \
               --load rope.asd \
               --eval '(ql:quickload :rope/test :silent t)' \
               --eval '(coveralls:with-coveralls () (asdf:test-system :rope/test))' \
               --eval '(quit)'